// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWkinHjB4-Np0Bp8ghzYvXpPfnK0Lh1uA',
    appId: '1:469070216649:web:d89740998cb10d380bbc18',
    messagingSenderId: '469070216649',
    projectId: 'dadlaga2025',
    authDomain: 'dadlaga2025.firebaseapp.com',
    storageBucket: 'dadlaga2025.firebasestorage.app',
    measurementId: 'G-6H90YHZ5V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCrCe0sh1QNvOaOIv6kt_-dKnJmb0t6yE',
    appId: '1:469070216649:android:957287c657b410420bbc18',
    messagingSenderId: '469070216649',
    projectId: 'dadlaga2025',
    storageBucket: 'dadlaga2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGkr85seA7ZFtWKB21vFVgf085a3XN_14',
    appId: '1:469070216649:ios:a9ce6785ad9dd7d60bbc18',
    messagingSenderId: '469070216649',
    projectId: 'dadlaga2025',
    storageBucket: 'dadlaga2025.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGkr85seA7ZFtWKB21vFVgf085a3XN_14',
    appId: '1:469070216649:ios:a9ce6785ad9dd7d60bbc18',
    messagingSenderId: '469070216649',
    projectId: 'dadlaga2025',
    storageBucket: 'dadlaga2025.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWkinHjB4-Np0Bp8ghzYvXpPfnK0Lh1uA',
    appId: '1:469070216649:web:36069865d93e162c0bbc18',
    messagingSenderId: '469070216649',
    projectId: 'dadlaga2025',
    authDomain: 'dadlaga2025.firebaseapp.com',
    storageBucket: 'dadlaga2025.firebasestorage.app',
    measurementId: 'G-GCYSD2BMCX',
  );

}